# # Manifiesto del Crate `infra_db`
#
# Este crate contiene la implementación concreta de la infraestructura.
# Es el "Cuerpo Técnico" que sabe cómo hablar con bases de datos y servicios externos.
#
# ## Responsabilidades
# - Implementar los repositorios definidos en `core_logic` usando SQLx (SQLite).
# - Implementar servicios externos como el hashing de contraseñas (Argon2).
# - Definir los modelos de base de datos (DTOs) y migraciones.
#
# ## Dependencias Clave
# - `sqlx`: Para la interacción con SQLite (ORM-like pero seguro).
# - `argon2`: Para el hashing seguro de contraseñas.
# - `tokio`: Runtime asíncrono para operaciones I/O no bloqueantes.

[package]
name = "infra_db"
version = "0.1.0"
edition = "2024"

[dependencies]
core_logic = { path = "../core_logic" } # Depende de la lógica de dominio

anyhow = "1.0"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite", "uuid", "chrono"] }
async-trait = "0.1"
tokio = { version = "1.43", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.11", features = ["v7", "serde"] }
chrono = { version = "0.4.39", features = ["serde"] }
argon2 = { version = "0.5", features = ["std"] }
rand = "0.8"
rand_core = { version = "0.6", features = ["std"] }
